In [2]:
# INITIAL SETUP
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# Database Connection
engine = create_engine('postgresql://postgres:gtsr@localhost:5432/vendor_performance')

In [13]:
# --- DATA AUDIT ---

query_tables = """
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
"""
tables = pd.read_sql(query_tables, con=engine)['table_name'].tolist()
tables

['begin_inventory',
 'end_inventory',
 'purchases',
 'purchase_prices',
 'sales',
 'vendor_invoice']

In [14]:
print("--- Database Audit ---")

for i in tables:
    print('-'*40, f'{i}', '-'*40)
    
    query1 = (f"""SELECT COUNT(*) FROM {i}""")
    query2 = (f"""SELECT * FROM {i} LIMIT 5""")
    
    temp1_df = pd.read_sql(query1, con=engine)
    temp2_df = pd.read_sql(query2, con=engine)
    
    print(f"Total Records: {temp1_df.iloc[0,0]} \nTotal Columns: {temp2_df.shape[1]}")
    print(temp2_df.dtypes)
    display(temp2_df.head(5))

--- Database Audit ---
---------------------------------------- begin_inventory ----------------------------------------
Total Records: 206529
Total Columns: 9
InventoryId     object
Store            int64
City            object
Brand            int64
Description     object
Size            object
onHand           int64
Price          float64
startDate       object
dtype: object

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

---------------------------------------- end_inventory ----------------------------------------
Total Records: 224489
Total Columns: 9
InventoryId     object
Store            int64
City            object
Brand            int64
Description     object
Size            object
onHand           int64
Price          float64
endDate         object
dtype: object

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

---------------------------------------- purchases ----------------------------------------
Total Records: 2372474
Total Columns: 16
InventoryId        object
Store               int64
Brand               int64
Description        object
Size               object
VendorNumber        int64
VendorName         object
PONumber            int64
PODate             object
ReceivingDate      object
InvoiceDate        object
PayDate            object
PurchasePrice     float64
Quantity            int64
Dollars           float64
Classification      int64
dtype: object

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,54_GUTHRAM_2062,54,2062,Woodford Reserve Bourbon,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-02,2024-01-09,2024-02-19,44.11,3,132.33,1
1,30_CULCHETH_3614,30,3614,Finlandia Vodka,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-01,2024-01-09,2024-02-19,15.99,6,95.94,1
2,38_GOULCREST_1060,38,1060,Jack Daniels Bruins Glass Pk,Liter,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-03,2024-01-09,2024-02-19,21.70,6,130.20,1
3,15_WANBORNE_2143,15,2143,Canadian Mist,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-01,2024-01-09,2024-02-19,10.07,5,50.35,1
4,69_MOUNTMEND_62,69,62,Herradura Silver Tequila,750mL,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-02,2024-01-09,2024-02-19,28.67,5,143.35,1

---------------------------------------- purchase_prices ----------------------------------------
Total Records: 12261
Total Columns: 9
Brand               int64
Description        object
Price             float64
Size               object
Volume             object
Classification      int64
PurchasePrice     float64
VendorNumber        int64
VendorName         object
dtype: object

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

---------------------------------------- sales ----------------------------------------
Total Records: 12825363
Total Columns: 14
InventoryId        object
Store               int64
Brand               int64
Description        object
Size               object
SalesQuantity       int64
SalesDollars      float64
SalesPrice        float64
SalesDate          object
Volume            float64
Classification      int64
ExciseTax         float64
VendorNo            int64
VendorName         object
dtype: object

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

---------------------------------------- vendor_invoice ----------------------------------------
Total Records: 5543
Total Columns: 10
VendorNumber      int64
VendorName       object
InvoiceDate      object
PONumber          int64
PODate           object
PayDate          object
Quantity          int64
Dollars         float64
Freight         float64
Approval         object
dtype: object

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [15]:
pd.read_sql_query(f"""SELECT * FROM purchases WHERE "VendorNumber" = 1128 LIMIT 5""", con=engine)

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,54_GUTHRAM_2062,54,2062,Woodford Reserve Bourbon,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-02,2024-01-09,2024-02-19,44.11,3,132.33,1
1,30_CULCHETH_3614,30,3614,Finlandia Vodka,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-01,2024-01-09,2024-02-19,15.99,6,95.94,1
2,38_GOULCREST_1060,38,1060,Jack Daniels Bruins Glass Pk,Liter,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-03,2024-01-09,2024-02-19,21.70,6,130.20,1
3,15_WANBORNE_2143,15,2143,Canadian Mist,1.75L,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-01,2024-01-09,2024-02-19,10.07,5,50.35,1
4,69_MOUNTMEND_62,69,62,Herradura Silver Tequila,750mL,1128,BROWN-FORMAN CORP,8150,2023-12-23,2024-01-02,2024-01-09,2024-02-19,28.67,5,143.35,1

In [17]:
pd.read_sql_query(f"""SELECT * FROM purchase_prices WHERE "VendorNumber" = 1128 LIMIT 5""", con=engine)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
1,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
2,171,Gentleman Jack,49.99,1750mL,1750,1,36.76,1128,BROWN-FORMAN CORP
3,809,Southern Comfort,17.99,1000mL,1000,1,13.13,1128,BROWN-FORMAN CORP
4,811,Jack Daniels No 7 Black,29.99,1000mL,1000,1,19.84,1128,BROWN-FORMAN CORP

In [18]:
pd.read_sql_query(f"""SELECT * FROM vendor_invoice WHERE "VendorNumber" = 1128 LIMIT 5""", con=engine)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,1128,BROWN-FORMAN CORP,2024-01-09,8150,2023-12-23,2024-02-19,4684,65403.57,1808.77,None
1,1128,BROWN-FORMAN CORP,2024-01-15,8210,2023-12-27,2024-02-25,23351,298902.89,1494.51,Frank Delahunt
2,1128,BROWN-FORMAN CORP,2024-01-26,8358,2024-01-06,2024-02-18,11443,138035.44,690.18,None
3,1128,BROWN-FORMAN CORP,2024-02-02,8457,2024-01-13,2024-02-29,12899,142492.97,755.21,None
4,1128,BROWN-FORMAN CORP,2024-02-06,8517,2024-01-18,2024-03-15,23217,335055.84,1708.78,Frank Delahunt

In [19]:
pd.read_sql_query(f"""SELECT * FROM sales WHERE "VendorNo" = 1128 LIMIT 5""", con=engine)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1051,1,1051,Woodford Reserve MC 1838,750mL,1,99.99,99.99,2024-01-04,750.0,1,0.79,1128,BROWN-FORMAN CORP
1,1_HARDERSFIELD_1051,1,1051,Woodford Reserve MC 1838,750mL,1,99.99,99.99,2024-01-23,750.0,1,0.79,1128,BROWN-FORMAN CORP
2,1_HARDERSFIELD_1060,1,1060,Jack Daniels Bruins Glass Pk,Liter,2,55.98,27.99,2024-01-01,1000.0,1,2.10,1128,BROWN-FORMAN CORP
3,1_HARDERSFIELD_1060,1,1060,Jack Daniels Bruins Glass Pk,Liter,1,27.99,27.99,2024-01-02,1000.0,1,1.05,1128,BROWN-FORMAN CORP
4,1_HARDERSFIELD_1060,1,1060,Jack Daniels Bruins Glass Pk,Liter,1,31.99,31.99,2024-01-11,1000.0,1,1.05,1128,BROWN-FORMAN CORP

In [20]:
query = """
SELECT "Brand", SUM("SalesQuantity") AS total_qty, SUM("SalesPrice") AS total_price, SUM("SalesDollars") AS total_dol
FROM sales
GROUP BY "Brand"
ORDER BY SUM("SalesDollars") DESC
"""

pd.read_sql(query,con=engine)

       Brand  total_qty  total_price   total_dol
0       1233   142049.0    672819.31  5101919.51
1       3405   160247.0    561512.37  4819073.49
2       8068   187140.0    461140.15  4538120.60
3       4261   200412.0    420050.01  4475972.88
4       3545   135838.0    545778.28  4223107.62
...      ...        ...          ...         ...
11232   9123        2.0         0.99        1.98
11233   3623        2.0         1.98        1.98
11234   3933        2.0         0.99        1.98
11235   2773        1.0         0.99        0.99
11236   5287        2.0         0.98        0.98

[11237 rows x 4 columns]

In [ ]:
# The CTE to join Sales, Purchases, Prices, and Freight into one Master Table

In [22]:
# --- STEP 2: CONSOLIDATED SQL QUERY (All Columns Restored) ---
# This CTE joins Sales, Purchases, Prices, and Freight into one Master Table
consolidated_query = """
WITH FreightSummary AS (
    SELECT "VendorNumber", SUM("Freight") as FreightCost 
    FROM vendor_invoice 
    GROUP BY "VendorNumber"
), 

PurchaseSummary AS (
    SELECT 
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price" AS ActualPrice,
        pp."Volume",
        SUM(p."Quantity") AS TotalPurchaseQuantity,
        SUM(p."Dollars") AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp ON p."Brand" = pp."Brand"
    WHERE p."PurchasePrice" > 0
    GROUP BY 
        p."VendorNumber", p."VendorName", p."Brand", p."Description", 
        p."PurchasePrice", pp."Price", pp."Volume"
), 

SalesSummary AS (
    SELECT 
        "VendorNo",
        "Brand",
        SUM("SalesQuantity") AS TotalSalesQuantity,
        SUM("SalesDollars") AS TotalSalesDollars,
        SUM("SalesPrice") AS TotalSalesPrice,
        SUM("ExciseTax") AS TotalExciseTax
    FROM sales
    GROUP BY "VendorNo", "Brand"
) 

SELECT 
    ps.*,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss 
    ON ps."VendorNumber" = ss."VendorNo" 
    AND ps."Brand" = ss."Brand"
LEFT JOIN FreightSummary fs 
    ON ps."VendorNumber" = fs."VendorNumber";
"""

In [23]:
# Load the consolidated data into a DataFrame
df_summary = pd.read_sql(consolidated_query, con=engine)

In [28]:
df_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,actualprice,Volume,totalpurchasequantity,totalpurchasedollars,totalsalesquantity,totalsalesdollars,totalsalesprice,totalexcisetax,freightcost
0,9552,M S WALKER INC,10937,Grahams 30-Yr Tawny Port,61.64,89.99,750,15.0,924.60,15.0,1349.85,899.90,1.66,55551.82
1,6785,PALM BAY INTERNATIONAL INC,18433,Bertani Amarone 04,62.91,94.99,750,7.0,440.37,63.0,5984.37,4654.51,6.93,13605.41
2,9552,M S WALKER INC,36571,Matanzas Creek Chard Sonoma,16.33,25.99,750,12.0,195.96,21.0,543.79,334.87,2.34,55551.82
3,90017,THE IMPORTED GRAPE LLC,45577,Pacifico Sur Chard Curico,2.80,5.29,750,72.0,201.60,69.0,503.01,87.48,7.75,80.03
4,2000,SOUTHERN WINE & SPIRITS NE,32137,F Coppola Diamond Znfd,9.39,15.99,750,1334.0,12526.26,1438.0,21723.62,15630.68,158.93,19016.59

In [26]:
df_summary.describe().T

,count,mean,std,min,25%,50%,75%,max
VendorNumber,10692.0,10650.649458,18753.519148,2.00,3951.0000,7153.000,9552.0000,201359.00
Brand,10692.0,18039.228769,12662.187074,58.00,5793.5000,18761.500,25514.2500,90631.00
PurchasePrice,10692.0,24.385303,109.269375,0.36,6.8400,10.455,19.4825,5681.81
actualprice,10692.0,35.643671,148.246016,0.49,10.9900,15.990,28.9900,7499.99
totalpurchasequantity,10692.0,3140.886831,11095.086769,1.00,36.0000,262.000,1975.7500,337660.00
totalpurchasedollars,10692.0,30106.693372,123067.799627,0.71,453.4575,3655.465,20738.2450,3811251.60
totalsalesquantity,10514.0,3129.583317,11037.801407,1.00,36.0000,280.000,1985.0000,334939.00
totalsalesdollars,10514.0,42954.173834,168977.755843,1.98,809.8200,5599.700,29524.2500,5101919.51
totalsalesprice,10514.0,19111.958773,45264.605387,0.99,334.8900,3020.085,16442.4775,672819.31
totalexcisetax,10514.0,1804.263569,11065.659557,0.06,5.3825,50.425,436.7300,368242.80
freightcost,10692.0,61433.763214,60938.458032,0.09,14069.8700,50293.620,79528.9900,257032.07

In [29]:
df_summary.shape

(10692, 14)

In [30]:
df_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
actualprice              float64
Volume                    object
totalpurchasequantity    float64
totalpurchasedollars     float64
totalsalesquantity       float64
totalsalesdollars        float64
totalsalesprice          float64
totalexcisetax           float64
freightcost              float64
dtype: object

In [32]:
df_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
actualprice                0
Volume                     0
totalpurchasequantity      0
totalpurchasedollars       0
totalsalesquantity       178
totalsalesdollars        178
totalsalesprice          178
totalexcisetax           178
freightcost                0
dtype: int64

In [33]:
df_summary.nunique()

VendorNumber               126
VendorName                 129
Brand                    10663
Description               9651
PurchasePrice             2150
actualprice                342
Volume                      31
totalpurchasequantity     3876
totalpurchasedollars      9844
totalsalesquantity        3808
totalsalesdollars         9616
totalsalesprice           9040
totalexcisetax            8043
freightcost                126
dtype: int64

In [34]:
df_summary['VendorName'].unique()

array(['M S WALKER INC             ', 'PALM BAY INTERNATIONAL INC ',
       'THE IMPORTED GRAPE LLC     ', 'SOUTHERN WINE & SPIRITS NE ',
       'E & J GALLO WINERY         ', 'MARTIGNETTI COMPANIES',
       'PSP WINES ', 'SAZERAC CO INC             ',
       'CAMPARI AMERICA            ', 'PERFECTA WINES             ',
       'DIAGEO NORTH AMERICA INC   ', 'MAJESTIC FINE WINES        ',
       'JIM BEAM BRANDS COMPANY    ', 'STELLAR IMPORTING CO LLC   ',
       'MHW LTD                    ', 'WINE GROUP INC             ',
       'STATE WINE & SPIRITS   ', 'LATITUDE BEVERAGE COMPANY  ',
       'Circa Wines                ', 'CONSTELLATION BRANDS INC   ',
       'VINILANDIA USA             ', 'DELICATO VINEYARDS INC     ',
       'STE MICHELLE WINE ESTATES  ', 'TREASURY WINE ESTATES      ',
       'PROXIMO SPIRITS INC.       ', 'ULTRA BEVERAGE COMPANY LLP ',
       'BROWN-FORMAN CORP          ', 'PREMIER DISTRIBUTORS       ',
       'KOBRAND CORPORATION        ', 'PERNOD RICARD USA          ',
       'DJINN SPIRITS LLC          ', 'MOET HENNESSY USA INC      ',
       'LUXCO INC                  ', 'SAZERAC NORTH AMERICA INC. ',
       'CANDIA VINEYARDS           ', 'WILLIAM GRANT & SONS INC   ',
       'SURVILLE ENTERPRISES CORP  ', 'BACARDI USA INC            ',
       'PINE STATE TRADING CO      ', 'MILTONS DISTRIBUTING CO    ',
       'FREDERICK WILDMAN & SONS   ', 'Russian Standard Vodka     ',
       'BANFI PRODUCTS CORP        ', 'TRINCHERO FAMILY ESTATES   ',
       'STOLI GROUP,(USA) LLC      ', 'REMY COINTREAU USA INC     ',
       'R.P.IMPORTS INC            ', 'SHAW ROSS INT L IMP LTD    ',
       'PHILLIPS PRODUCTS CO.      ', 'VRANKEN AMERICA            ',
       'CASTLE BRANDS CORP.        ', 'SEA HAGG DISTILLERY LLC    ',
       'SIDNEY FRANK IMPORTING CO  ', 'FORTUNE WINE BROKERS LLC   ',
       'VINEYARD BRANDS INC        ', 'SEA BREEZE CELLARS LLC     ',
       'HEAVEN HILL DISTILLERIES   ', 'DIAGEO CHATEAU ESTATE WINES',
       'JEWELL TOWNE VINEYARDS     ', 'MOONLIGHT MEADERY          ',
       'PREMIUM PORT WINES, INC.   ', 'CRUSH WINES                ',
       'TY KU LLC                  ', 'MCCORMICK DISTILLING CO    ',
       'Dunn Wine Brokers          ', 'EDRINGTON AMERICAS         ',
       'LAIRD & CO                 ', 'OLE SMOKY DISTILLERY LLC   ',
       'CHARLES JACQUIN ET CIE INC ', 'BRONCO WINE COMPANY        ',
       'VINEXTRA INC               ', 'BULLY BOY DISTILLERS       ',
       'NICHE W & S                ', 'GILMANTON WINERY & VINEYARD',
       'WESTERN SPIRITS BEVERAGE CO', 'TAMWORTH DISTILLING        ',
       'LABELLE VYDS AND WINERY    ', 'UNCORKED       ',
       'SOUTHERN GLAZERS W&S OF NE ', 'TRUETT HURST               ',
       'KLIN SPIRITS LLC           ', 'FLAG HILL WINERY & VINEYARD',
       'POVERTY LANE ORCHARDS      ', 'FULCHINO VINEYARD INC      ',
       'HOOD RIVER DISTILLERS, Inc.', 'Serralles Usa LLC          ',
       'INCREDIBREW INC            ', 'ZORVINO VINEYARDS          ',
       'CALEDONIA SPIRITS INC      ', 'THE PIERPONT GROUP LLC     ',
       'LOYAL DOG WINERY           ', 'DUGGANS DISTILLED PRODUCTS ',
       'HIGHLAND WINE MERCHANTS LLC', 'APPOLO VINEYARDS LLC       ',
       'DISARONNO INTERNATIONAL LLC', 'FABRIZIA SPIRITS LLC       ',
       'BLACK PRINCE DISTILLERY INC', 'MARTIGNETTI COMPANIES ',
       'STARK BREWING COMPANY      ', 'MARSALLE COMPANY           ',
       'TAKARA SAKE USA INC        ', 'FANTASY FINE WINES CORP    ',
       'AMERICAN VINTAGE BEVERAGE  ', 'PARK STREET IMPORTS LLC    ',
       'WEIN BAUER INC             ', 'VINEYARD BRANDS LLC        ',
       'SMOKY QUARTZ DISTILLERY LLC', 'AMERICAN SPIRITS EXCHANGE  ',
       'CENTEUR IMPORTS LLC        ', 'ALTAMAR BRANDS LLC         ',
       'ALISA CARR BEVERAGES           ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'SWEETWATER FARM         ', 'ATLANTIC IMPORTING COMPANY ',
       'SWEET BABY VINEYARD        ', 'VINEDREA WINES LLC         ',
       'TALL SHIP DISTILLERY LLC   ', 'CAPSTONE INTERNATIONAL     ',
       'FLAVOR ESSENCE INC         ', 'LAUREATE IMPORTS CO        ',
       'BLACK ROCK SPIRITS LLC     ', 'HAUNTING WHISPER VYDS      ',
       'ADAMBA IMPORTS INTL INC    ', 'MANGO BOTTLING INC         ',
       'BLACK COVE BEVERAGES       ', 'WALPOLE MTN VIEW WINERY    ',
       'STAR INDUSTRIES INC.       ', 'SILVER MOUNTAIN CIDERS     ',
       'AAPER ALCOHOL & CHEMICAL CO'], dtype=object)

In [35]:
df_summary['Description'].unique()

array(['Grahams 30-Yr Tawny Port', 'Bertani Amarone 04',
       'Matanzas Creek Chard Sonoma', ..., 'Tilia Bonarda Mendoza',
       'Fortant Heritage Lang Rouge', 'Darkhorse Cab Svgn'],
      shape=(9651,), dtype=object)

In [33]:
# --- DATA CLEANING ---

# 1. Fill NaNs (Items bought but not yet sold should have 0 sales, not NaN)
cols_to_fix = ['totalsalesquantity', 'totalsalesdollars', 'totalsalesprice', 'totalexcisetax']
df_summary[cols_to_fix] = df_summary[cols_to_fix].fillna(0)

In [34]:
# 2. Correcting Volume's datatype
df_summary['Volume'] = df_summary['Volume'].astype('float64')

# 3. Cleaning the Empty Space in Vendor's Name
df_summary['VendorName'] = df_summary['VendorName'].str.strip()

In [35]:
# --- FEATURE ENGINEERING ---

# 1. Gross Profit = Sales Revenue - Cost of Goods Sold
# Note: We use 'TotalPurchaseDollars' as our cost basis here

df_summary['GrossProfit'] = df_summary['totalsalesdollars'] - df_summary['totalpurchasedollars']

In [36]:
# 2. Profit Margin % Calculation
# Handling division by zero using np.where

df_summary['ProfitMargin'] = np.where(
    df_summary['totalsalesdollars'] > 0, 
    (df_summary['GrossProfit'] / df_summary['totalsalesdollars']) * 100, 
    0
)

In [37]:
# 3. Inventory Related Features

# Unsold Inventory
df_summary['UnsoldInventory'] = df_summary['totalpurchasequantity'] - df_summary['totalsalesquantity']

# Stock Turnover
df_summary['StockTurnover'] = df_summary['totalsalesquantity'] / df_summary['totalpurchasequantity']

# Sales To Purchase Ratio
df_summary['SalesToPurchaseRatio'] = df_summary['totalsalesdollars'] / df_summary['totalpurchasedollars']

In [38]:
df_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,actualprice,Volume,totalpurchasequantity,totalpurchasedollars,totalsalesquantity,totalsalesdollars,totalsalesprice,totalexcisetax,freightcost,GrossProfit,ProfitMargin,UnsoldInventory,StockTurnover,SalesToPurchaseRatio
0,9552,M S WALKER INC,10937,Grahams 30-Yr Tawny Port,61.64,89.99,750.0,15.0,924.60,15.0,1349.85,899.90,1.66,55551.82,425.25,31.503500,0.0,1.000000,1.459929
1,6785,PALM BAY INTERNATIONAL INC,18433,Bertani Amarone 04,62.91,94.99,750.0,7.0,440.37,63.0,5984.37,4654.51,6.93,13605.41,5544.00,92.641331,-56.0,9.000000,13.589413
2,9552,M S WALKER INC,36571,Matanzas Creek Chard Sonoma,16.33,25.99,750.0,12.0,195.96,21.0,543.79,334.87,2.34,55551.82,347.83,63.964030,-9.0,1.750000,2.775005
3,90017,THE IMPORTED GRAPE LLC,45577,Pacifico Sur Chard Curico,2.80,5.29,750.0,72.0,201.60,69.0,503.01,87.48,7.75,80.03,301.41,59.921274,3.0,0.958333,2.495089
4,2000,SOUTHERN WINE & SPIRITS NE,32137,F Coppola Diamond Znfd,9.39,15.99,750.0,1334.0,12526.26,1438.0,21723.62,15630.68,158.93,19016.59,9197.36,42.338063,-104.0,1.077961,1.734246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,10754,PERFECTA WINES,25381,Selbach-Oster Riesling,11.64,16.99,750.0,6.0,69.84,89.0,1512.11,1121.34,9.83,28720.52,1442.27,95.381288,-83.0,14.833333,21.651060
10688,9744,FREDERICK WILDMAN & SONS,25425,La Scolca Black Label Gavi,24.82,35.99,750.0,12.0,297.84,12.0,431.88,35.99,1.35,3999.93,134.04,31.036399,0.0,1.000000,1.450040
10689,9552,M S WALKER INC,25544,Tilia Bonarda Mendoza,7.94,11.99,750.0,1171.0,9297.74,807.0,8553.93,4977.35,89.61,55551.82,-743.81,-8.695535,364.0,0.689155,0.920001
10690,10754,PERFECTA WINES,26442,Fortant Heritage Lang Rouge,10.80,15.99,750.0,2477.0,26751.60,1462.0,23377.38,11688.69,162.81,28720.52,-3374.22,-14.433696,1015.0,0.590230,0.873868
10691,3252,E & J GALLO WINERY,17876,Darkhorse Cab Svgn,5.33,7.99,750.0,9368.0,49931.44,9179.0,73340.21,32511.31,1023.94,61966.91,23408.77,31.918057,189.0,0.979825,1.468818

In [40]:
# --- SAVING TO DATABASE FOR ADVANCED ANALYSIS ---

# We save this final table as 'vendor_summary'

df_summary.to_sql('vendor_summary', con=engine, if_exists='replace', index=False)

print("\n✅ Success! Cleaned table 'vendor_summary' created in PostgreSQL.")

✅ Success! Cleaned table 'vendor_summary' created in PostgreSQL.

In [41]:
df_summary.describe().T

,count,mean,std,min,25%,50%,75%,max
VendorNumber,10692.0,10650.649458,18753.519148,2.000000,3951.000000,7153.000000,9552.000000,2.013590e+05
Brand,10692.0,18039.228769,12662.187074,58.000000,5793.500000,18761.500000,25514.250000,9.063100e+04
PurchasePrice,10692.0,24.385303,109.269375,0.360000,6.840000,10.455000,19.482500,5.681810e+03
actualprice,10692.0,35.643671,148.246016,0.490000,10.990000,15.990000,28.990000,7.499990e+03
Volume,10692.0,847.360550,664.309212,50.000000,750.000000,750.000000,750.000000,2.000000e+04
totalpurchasequantity,10692.0,3140.886831,11095.086769,1.000000,36.000000,262.000000,1975.750000,3.376600e+05
totalpurchasedollars,10692.0,30106.693372,123067.799627,0.710000,453.457500,3655.465000,20738.245000,3.811252e+06
totalsalesquantity,10692.0,3077.482136,10952.851391,0.000000,33.000000,261.000000,1929.250000,3.349390e+05
totalsalesdollars,10692.0,42239.074419,167655.265984,0.000000,729.220000,5298.045000,28396.915000,5.101920e+06
totalsalesprice,10692.0,18793.783627,44952.773386,0.000000,289.710000,2857.800000,16059.562500,6.728193e+05
totalexcisetax,10692.0,1774.226259,10975.582240,0.000000,4.800000,46.570000,418.650000,3.682428e+05
freightcost,10692.0,61433.763214,60938.458032,0.090000,14069.870000,50293.620000,79528.990000,2.570321e+05
GrossProfit,10692.0,12132.381048,46224.337964,-52002.780000,52.920000,1399.640000,8660.200000,1.290668e+06
ProfitMargin,10692.0,-15.620770,443.555329,-23730.638953,13.324515,30.405457,39.956135,9.971666e+01
UnsoldInventory,10692.0,63.404695,586.128159,-13304.000000,-12.000000,10.000000,66.000000,1.312100e+04
StockTurnover,10692.0,1.706793,6.020460,0.000000,0.807229,0.981529,1.039342,2.745000e+02
SalesToPurchaseRatio,10692.0,2.504390,8.459067,0.000000,1.153729,1.436894,1.665449,3.529286e+02